### ISSUE TITLE
apt-get (apt) for rustc and curl instead of snap

### ISSUE THREAD

**Issue by Sascha-1** [safenetwork-community/comnet-install#6]
I'm not sure if there is a difference between apt and apt-get. The man pages are different. Maybe apt-get is safer?

On an updated Linux Mint, installing rustc and curl from the main repositories works fine. Is snap necessary?

Maybe do all the apt-get installing right at the beginning of the script, along with a specific warning that only the apt-get installation requires root privileges?

**Comment by willief** [comment]
https://phoenixnap.com/kb/apt-vs-apt-get  explains the differences. IMHO use apt rather than apt-get.  BUT https://phoenixnap.com/kb/snap-vs-apt explains apt vs snap. I think for the use case here n00bs, KISS then snap is more appropriate - having said that I dont think there really is any great advantage either way in this case.  Other than "Snap is the future, apt is the past" which may or may not be true but I see much more snap activity these days.

The dependencies installation was split in case I decided later  to make Rust and vdash an optional part of the process.  The Rust and vdash download/installl could get moved to the start fairly easily I think as this is a n00b script and we want a fairly instant result so they get given a nice UI to look at as their node processes chunks.
